# Assignment No. 9

## Anas Sohail

In [1]:
#Create a NumPy array and perform various operations like addition, subtraction, multiplication, and division.

import numpy as np

# Creating two NumPy arrays
array1 = np.array([23, 43, 54, 65, 77])
array2 = np.array([44, 33, 65, 23, 54])

# Addition
addition = array1 + array2

# Subtraction
subtraction = array1 - array2

# Multiplication
multiplication = array1 * array2

# Division
division = array1 / array2

# Displaying the results
print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Array 1: [23 43 54 65 77]
Array 2: [44 33 65 23 54]
Addition: [ 67  76 119  88 131]
Subtraction: [-21  10 -11  42  23]
Multiplication: [1012 1419 3510 1495 4158]
Division: [0.52272727 1.3030303  0.83076923 2.82608696 1.42592593]


In [6]:
#Explore indexing and slicing to access specific elements or subsets of the array.

import numpy as np

# Creating a 2D NumPy array
array = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

print("Original Array:\n", array)

#Accessing specific elements through Indexing
element_1 = array[1, 2]
element_2 = array[2, 0]

# Slicing: Accessing subsets
row_1 = array[0, 0:2]
col_1 = array[1:3, 2]      
sub_array = array[1:3, 1:2] 

# Negative indexing
last_element = array[-1, -1]  # Accessing the last element (90)

# Displaying the results
print("\nSpecific elements:")
print("Element at [0, 1]:", element_1)
print("Element at [2, 2]:", element_2)

print("\nSlicing results:")
print("First row:", row_1)
print("First column:", col_1)
print("Sub-array:\n", sub_array)

print("\nNegative Indexing result:")
print("Last element:", last_element)

Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Specific elements:
Element at [0, 1]: 60
Element at [2, 2]: 70

Slicing results:
First row: [10 20]
First column: [60 90]
Sub-array:
 [[50]
 [80]]

Negative Indexing result:
Last element: 90


In [8]:
# Practice reshaping arrays and transposing matrices.
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshaping the 1D array into a 3x3 2D array
array_reshaped = array_1d.reshape(3, 3)

# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transposing the matrix
matrix_transposed = matrix.T

# Displaying results
print("Original 1D Array:\n", array_1d)
print("\nReshaped Array:\n", array_reshaped)

print("\nOriginal Matrix:\n", matrix)
print("\nTransposed Matrix:\n", matrix_transposed)

Original 1D Array:
 [1 2 3 4 5 6 7 8 9]

Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
#Use NumPy functions to calculate statistics like mean, median, standard deviation, and variance.
import numpy as np

# Creating a NumPy array
data = np.array([23, 43, 33, 67, 62, 54])

# Calculating Mean
mean_value = np.mean(data)

# Calculating Median
median_value = np.median(data)

# Calculating Standard Deviation
std_deviation = np.std(data)

# Calculating Variance
variance_value = np.var(data)

# Displaying the results
print("Data:", data)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance_value)

Data: [23 43 33 67 62 54]

Mean: 47.0
Median: 48.5
Standard Deviation: 15.609825965290794
Variance: 243.66666666666666


In [11]:
# Create arrays with different data types (e.g., int, float, bool, str).
import numpy as np

# Creating an integer array
int_array = np.array([1, 2, 3, 4])

# Creating a float array
float_array = np.array([1.1, 2.2, 3.3, 4.4])

# Creating a boolean array
bool_array = np.array([True, False, True, False])

# Creating a string array
str_array = np.array(["apple", "banana", "cherry"])

# Displaying the arrays and their data types
print("Integer Array:", int_array)
print("Data Type of Integer Array:", int_array.dtype)

print("\nFloat Array:", float_array)
print("Data Type of Float Array:", float_array.dtype)

print("\nBoolean Array:", bool_array)
print("Data Type of Boolean Array:", bool_array.dtype)

print("\nString Array:", str_array)
print("Data Type of String Array:", str_array.dtype)

Integer Array: [1 2 3 4]
Data Type of Integer Array: int32

Float Array: [1.1 2.2 3.3 4.4]
Data Type of Float Array: float64

Boolean Array: [ True False  True False]
Data Type of Boolean Array: bool

String Array: ['apple' 'banana' 'cherry']
Data Type of String Array: <U6


In [12]:
#Concatenate arrays.
import numpy as np

# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating 1D arrays
concat_1d = np.concatenate((array1, array2))

# Creating two 2D arrays
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])

# Concatenating 2D arrays along axis 0 (rows)
concat_axis0 = np.concatenate((array3, array4), axis=0)

# Concatenating 2D arrays along axis 1 (columns)
concat_axis1 = np.concatenate((array3, array4), axis=1)

# Displaying results
print("1D Array 1:", array1)
print("1D Array 2:", array2)
print("Concatenated 1D Array:", concat_1d)

print("\n2D Array 1:\n", array3)
print("2D Array 2:\n", array4)
print("Concatenated 2D Array (Axis 0 - Rows):\n", concat_axis0)
print("Concatenated 2D Array (Axis 1 - Columns):\n", concat_axis1)

1D Array 1: [1 2 3]
1D Array 2: [4 5 6]
Concatenated 1D Array: [1 2 3 4 5 6]

2D Array 1:
 [[1 2]
 [3 4]]
2D Array 2:
 [[5 6]
 [7 8]]
Concatenated 2D Array (Axis 0 - Rows):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated 2D Array (Axis 1 - Columns):
 [[1 2 5 6]
 [3 4 7 8]]


In [1]:
# Sort arrays in ascending or descending order.

import numpy as np

# Creating a 1D array
array_1d = np.array([10, 4, 7, 1, 9, 3])

# Sorting the array in ascending order
sorted_array_asc = np.sort(array_1d)

# Sorting the array in descending order
sorted_array_desc = np.sort(array_1d)[::-1]


# Displaying results
print("Original Array:", array_1d)
print("Sorted Array (Ascending):", sorted_array_asc)
print("Sorted Array (Descending):", sorted_array_desc)


Original Array: [10  4  7  1  9  3]
Sorted Array (Ascending): [ 1  3  4  7  9 10]
Sorted Array (Descending): [10  9  7  4  3  1]


In [10]:
# Load data from various sources (e.g., CSV, Excel, JSON).
import pandas as pd

# Loading data from a CSV file
csv_data = pd.read_csv('retail supermarket.csv')

# Displaying the first and last few rows of the CSV data
csv_data

Ship Mode    Segment        Country             City       State  \
0       Second Class   Consumer  United States        Henderson    Kentucky   
1       Second Class   Consumer  United States        Henderson    Kentucky   
2       Second Class  Corporate  United States      Los Angeles  California   
3     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
4     Standard Class   Consumer  United States  Fort Lauderdale     Florida   
...              ...        ...            ...              ...         ...   
9989    Second Class   Consumer  United States            Miami     Florida   
9990  Standard Class   Consumer  United States       Costa Mesa  California   
9991  Standard Class   Consumer  United States       Costa Mesa  California   
9992  Standard Class   Consumer  United States       Costa Mesa  California   
9993    Second Class   Consumer  United States      Westminster  California   

      Postal Code Region         Category Sub-Category     Sales  Quantity  \
0           42420  South        Furniture    Bookcases  261.9600         2   
1           42420  South        Furniture       Chairs  731.9400         3   
2           90036   West  Office Supplies       Labels   14.6200         2   
3           33311  South        Furniture       Tables  957.5775         5   
4           33311  South  Office Supplies      Storage   22.3680         2   
...           ...    ...              ...          ...       ...       ...   
9989        33180  South        Furniture  Furnishings   25.2480         3   
9990        92627   West        Furniture  Furnishings   91.9600         2   
9991        92627   West       Technology       Phones  258.5760         2   
9992        92627   West  Office Supplies        Paper   29.6000         4   
9993        92683   West  Office Supplies   Appliances  243.1600         2   

      Discount    Profit  
0         0.00   41.9136  
1         0.00  219.5820  
2         0.00    6.8714  
3         0.45 -383.0310  
4         0.20    2.5164  
...        ...       ...  
9989      0.20    4.1028  
9990      0.00   15.6332  
9991      0.20   19.3932  
9992      0.00   13.3200  
9993      0.00   72.9480  

[9994 rows x 13 columns]

In [12]:
# Explore the structure of a DataFrame, including its shape, data types, and missing values.
import pandas as pd

# Example DataFrame
data = {
    'Name': ['Anas', 'Huda', 'Ghulam', 'Ubaid', None],
    'Age': [25, 30, None, 22, 29],
    'Salary': [50000, 60000, 55000, 58000, None],
    'Department': ['HR', 'Finance', 'IT', None, 'IT']
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print("DataFrame:\n", df)

# 1. Check the shape of the DataFrame
print("\nShape of DataFrame:", df.shape)

# 2. Check the data types of each column
print("\nData Types:\n", df.dtypes)

# 3. Get an overview of the DataFrame with info()
print("\nDataFrame Info:")
print(df.info())

# 4. Checking for missing values
print("\nMissing Values:\n", df.isnull().sum())


# Getting descriptive statistics for numerical columns
descriptive_stats = df.describe()

# Displaying the descriptive statistics
print("\nDescriptive Statistics:\n", descriptive_stats)

DataFrame:
      Name   Age   Salary Department
0    Anas  25.0  50000.0         HR
1    Huda  30.0  60000.0    Finance
2  Ghulam   NaN  55000.0         IT
3   Ubaid  22.0  58000.0       None
4    None  29.0      NaN         IT

Shape of DataFrame: (5, 4)

Data Types:
 Name           object
Age           float64
Salary        float64
Department     object
dtype: object

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        4 non-null      object 
 1   Age         4 non-null      float64
 2   Salary      4 non-null      float64
 3   Department  4 non-null      object 
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes
None

Missing Values:
 Name          1
Age           1
Salary        1
Department    1
dtype: int64

Descriptive Statistics:
              Age       Salary
count   4.000000      4.00000
mean   26.500000  5575

In [13]:
# Filter and select specific columns or rows.

import pandas as pd

# Example DataFrame
data = {
    'Name': ['Anas', 'Huda', 'Ghulam', 'Ubaid', None],
    'Age': [25, 30, None, 22, 29],
    'Salary': [50000, 60000, 55000, 58000, None],
    'Department': ['HR', 'Finance', 'IT', None, 'IT']
}

df = pd.DataFrame(data)

# Displaying the DataFrame
print("DataFrame:\n", df)

# Selecting specific columns
selected_columns = df[['Name', 'Salary']]

# Displaying the selected columns
print("Selected Columns (Name and Salary):\n", selected_columns)

DataFrame:
      Name   Age   Salary Department
0    Anas  25.0  50000.0         HR
1    Huda  30.0  60000.0    Finance
2  Ghulam   NaN  55000.0         IT
3   Ubaid  22.0  58000.0       None
4    None  29.0      NaN         IT
Selected Columns (Name and Salary):
      Name   Salary
0    Anas  50000.0
1    Huda  60000.0
2  Ghulam  55000.0
3   Ubaid  58000.0
4    None      NaN
